name: AW2 Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o aw2_linux

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o aw2.exe

    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o aw2_macos

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          aw2_linux
          aw2.exe
          aw2_macos
